// ═══════════════════════════════════════
// ORACLE — Export Utilities
// Export to PDF, Word (.docx), CSV, Markdown, Plain Text with ORACLE branding
// ═══════════════════════════════════════

import jsPDF from 'jspdf';

// ─── Branding ─────────────────────────

const BRAND = {
  name: 'ORACLE',
  tagline: 'Universal Agency Intelligence',
  primaryColor: [99, 102, 241] as const, // Indigo
  successColor: [16, 185, 129] as const,
  warningColor: [245, 158, 11] as const,
  errorColor: [239, 68, 68] as const,
  textColor: [15, 16, 32] as const,
  mutedColor: [120, 128, 160] as const,
  surfaceColor: [248, 250, 255] as const,
};

// ─── PDF Export ────────────────────────

export interface PDFExportOptions {
  title: string;
  subtitle?: string;
  sections: PDFSection[];
  fileName?: string;
  showBranding?: boolean;
}

export interface PDFSection {
  heading: string;
  content: string;
  type?: 'text' | 'table' | 'list';
  tableHeaders?: string[];
  tableRows?: string[][];
  listItems?: string[];
}

/**
 * Export content as a professionally branded PDF document
 */
export function exportToPDF(options: PDFExportOptions): void {
  const { title, subtitle, sections, fileName, showBranding = true } = options;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Header ──
  if (showBranding) {
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.primaryColor);
    doc.text(BRAND.name, margin, y + 5);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.mutedColor);
    doc.text(BRAND.tagline, margin, y + 11);

    // Right-aligned date
    doc.setFontSize(8);
    doc.text(new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }), pageWidth - margin, y + 5, { align: 'right' });

    y += 18;
    doc.setDrawColor(...BRAND.primaryColor);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  }

  // ── Title ──
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.textColor);
  doc.text(title, margin, y);
  y += 8;

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.mutedColor);
    doc.text(subtitle, margin, y);
    y += 8;
  }

  y += 4;

  // ── Sections ──
  for (const section of sections) {
    // Check for page break
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    // Section heading
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BRAND.primaryColor);
    doc.text(section.heading, margin, y);
    y += 7;

    if (section.type === 'table' && section.tableHeaders && section.tableRows) {
      // Table
      y = renderPDFTable(doc, y, margin, contentWidth, section.tableHeaders, section.tableRows);
    } else if (section.type === 'list' && section.listItems) {
      // List
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.textColor);
      for (const item of section.listItems) {
        if (y > 270) { doc.addPage(); y = margin; }
        const lines = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
        for (const line of lines) {
          doc.text(line, margin + 3, y);
          y += 5;
        }
        y += 1;
      }
    } else {
      // Text
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...BRAND.textColor);
      const lines = doc.splitTextToSize(section.content, contentWidth);
      for (const line of lines) {
        if (y > 270) { doc.addPage(); y = margin; }
        doc.text(line, margin, y);
        y += 5;
      }
    }

    y += 6;
  }

  // ── Footer ──
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.mutedColor);
    doc.text(`Generated by ${BRAND.name} — ${BRAND.tagline}`, margin, 290);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 290, { align: 'right' });
  }

  const safeFileName = (fileName || title).replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
  doc.save(`${safeFileName}-${Date.now()}.pdf`);
}

function renderPDFTable(
  doc: jsPDF,
  startY: number,
  x: number,
  width: number,
  headers: string[],
  rows: string[][]
): number {
  const colWidth = width / headers.length;
  let y = startY;

  // Header row
  doc.setFillColor(...BRAND.surfaceColor);
  doc.rect(x, y - 4, width, 8, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.textColor);
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x + i * colWidth + 2, y);
  }
  y += 8;

  // Data rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  for (const row of rows) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setTextColor(...BRAND.textColor);
    for (let i = 0; i < row.length; i++) {
      const cellText = doc.splitTextToSize(row[i], colWidth - 4)[0] || '';
      doc.text(cellText, x + i * colWidth + 2, y);
    }
    y += 6;
  }

  return y + 4;
}

// ─── Word (.docx) Export ───────────────

export interface DocxExportOptions {
  title: string;
  subtitle?: string;
  sections: DocxSection[];
  fileName?: string;
}

export interface DocxSection {
  heading: string;
  content: string;
  type?: 'text' | 'list' | 'table';
  listItems?: string[];
  tableHeaders?: string[];
  tableRows?: string[][];
}

/**
 * Export content as a .docx file (HTML-based approach for browser compatibility).
 * Creates a rich HTML document that Word can open natively.
 */
export function exportToWord(options: DocxExportOptions): void {
  const { title, subtitle, sections, fileName } = options;

  let html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: 'Calibri', sans-serif; margin: 40px; color: #0f1020; line-height: 1.5; }
  .brand { color: #6366f1; font-size: 24px; font-weight: bold; margin-bottom: 4px; }
  .tagline { color: #7080b0; font-size: 11px; margin-bottom: 20px; }
  h1 { color: #0f1020; font-size: 22px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; margin-top: 30px; }
  h2 { color: #6366f1; font-size: 16px; margin-top: 24px; }
  .subtitle { color: #7080b0; font-size: 12px; margin-bottom: 16px; }
  .date { color: #7080b0; font-size: 10px; float: right; margin-top: -30px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 11px; }
  th { background: #f0f4ff; padding: 8px 12px; text-align: left; border: 1px solid #dde5ff; font-weight: 600; }
  td { padding: 6px 12px; border: 1px solid #e8eeff; }
  ul { margin: 8px 0; padding-left: 20px; }
  li { margin: 4px 0; font-size: 12px; }
  p { font-size: 12px; margin: 6px 0; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e8eeff; color: #7080b0; font-size: 9px; }
</style>
</head>
<body>
<div class="brand">ORACLE</div>
<div class="tagline">Universal Agency Intelligence</div>
<div class="date">${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>

<h1>${title}</h1>
${subtitle ? `<div class="subtitle">${subtitle}</div>` : ''}
`;

  for (const section of sections) {
    html += `<h2>${section.heading}</h2>`;

    if (section.type === 'table' && section.tableHeaders && section.tableRows) {
      html += '<table>';
      html += '<tr>' + section.tableHeaders.map((h) => `<th>${h}</th>`).join('') + '</tr>';
      for (const row of section.tableRows) {
        html += '<tr>' + row.map((c) => `<td>${c}</td>`).join('') + '</tr>';
      }
      html += '</table>';
    } else if (section.type === 'list' && section.listItems) {
      html += '<ul>' + section.listItems.map((item) => `<li>${item}</li>`).join('') + '</ul>';
    } else {
      html += `<p>${section.content.replace(/\n/g, '<br>')}</p>`;
    }
  }

  html += `
<div class="footer">
  Generated by ORACLE — Universal Agency Intelligence · ${new Date().toLocaleDateString('en-IN')}
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(fileName || title).replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-${Date.now()}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── CSV Export ────────────────────────

export interface CSVExportOptions {
  headers: string[];
  rows: string[][];
  fileName: string;
}

/**
 * Export data as a CSV file
 */
export function exportToCSV(options: CSVExportOptions): void {
  const { headers, rows, fileName } = options;

  const escapeCSV = (value: string): string => {
    if (value.includes(',') || value.includes('"') || value.includes('\n')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  };

  const lines = [
    headers.map(escapeCSV).join(','),
    ...rows.map((row) => row.map(escapeCSV).join(',')),
  ];

  const csv = lines.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Markdown Export ───────────────────

export interface MarkdownExportOptions {
  title: string;
  sections: Array<{ heading: string; content: string }>;
  fileName: string;
}

/**
 * Export content as a Markdown file
 */
export function exportToMarkdown(options: MarkdownExportOptions): void {
  const { title, sections, fileName } = options;

  const lines = [
    `# ${title}`,
    '',
    `*Generated by ORACLE — ${new Date().toLocaleDateString('en-IN')}*`,
    '',
  ];

  for (const section of sections) {
    lines.push(`## ${section.heading}`, '', section.content, '');
  }

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${fileName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Copy as Text ──────────────────────

/**
 * Copy text content to clipboard
 */
export async function copyAsPlainText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

/**
 * Copy markdown content to clipboard
 */
export async function copyAsMarkdown(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch {
    return false;
  }
}

// ─── Chat Export ───────────────────────

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
}

/**
 * Export a conversation as PDF with ORACLE branding
 */
export function exportChatToPDF(messages: ChatMessage[], title: string): void {
  const sections: PDFSection[] = messages.map((msg) => ({
    heading: msg.role === 'user' ? '💬 User' : '⚡ ORACLE',
    content: msg.content,
    type: 'text' as const,
  }));

  exportToPDF({
    title,
    subtitle: `${messages.length} messages · Exported ${new Date().toLocaleDateString('en-IN')}`,
    sections,
    fileName: `chat-${title}`,
  });
}

/**
 * Export a conversation as Word document
 */
export function exportChatToWord(messages: ChatMessage[], title: string): void {
  const sections: DocxSection[] = messages.map((msg) => ({
    heading: msg.role === 'user' ? '💬 User' : '⚡ ORACLE',
    content: msg.content,
    type: 'text' as const,
  }));

  exportToWord({
    title,
    subtitle: `${messages.length} messages · Exported ${new Date().toLocaleDateString('en-IN')}`,
    sections,
    fileName: `chat-${title}`,
  });
}

/**
 * Export a conversation as Markdown
 */
export function exportChatToMarkdown(messages: ChatMessage[], title: string): void {
  const sections = messages.map((msg) => ({
    heading: msg.role === 'user' ? '💬 You' : '⚡ ORACLE',
    content: msg.content,
  }));

  exportToMarkdown({ title, sections, fileName: `chat-${title}` });
}

/**
 * Export a conversation as CSV
 */
export function exportChatToCSV(messages: ChatMessage[], title: string): void {
  exportToCSV({
    headers: ['Role', 'Message', 'Timestamp'],
    rows: messages.map((msg) => [
      msg.role,
      msg.content.replace(/\n/g, ' '),
      new Date(msg.timestamp).toLocaleString('en-IN'),
    ]),
    fileName: `chat-${title}`,
  });
}

/**
 * Generate plain text representation of a conversation
 */
export function chatToPlainText(messages: ChatMessage[], title: string): string {
  const lines = [
    `${title}`,
    `${'='.repeat(title.length)}`,
    `Exported: ${new Date().toLocaleString('en-IN')}`,
    '',
  ];

  for (const msg of messages) {
    const role = msg.role === 'user' ? 'You' : 'ORACLE';
    const time = new Date(msg.timestamp).toLocaleTimeString('en-IN');
    lines.push(`[${time}] ${role}:`, msg.content, '');
  }

  return lines.join('\n');
}

/**
 * Generate markdown representation of a conversation
 */
export function chatToMarkdown(messages: ChatMessage[], title: string): string {
  const lines = [
    `# ${title}`,
    '',
    `*Exported: ${new Date().toLocaleString('en-IN')}*`,
    '',
    '---',
    '',
  ];

  for (const msg of messages) {
    const role = msg.role === 'user' ? '👤 **You**' : '⚡ **ORACLE**';
    lines.push(`${role}:`, '', msg.content, '', '---', '');
  }

  return lines.join('\n');
}

// ─── Table Export (Generic) ────────────

/**
 * Export a data table as CSV with auto-generated headers
 */
export function exportTableToCSV(
  data: Record<string, string | number>[],
  fileName: string
): void {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const rows = data.map((row) => headers.map((h) => String(row[h] ?? '')));
  exportToCSV({ headers, rows, fileName });
}
