// ═══════════════════════════════════════
// ORACLE — Invoice PDF Generator
// Professional Indian invoices · GST compliance · PDF + DOCX export
// ═══════════════════════════════════════

import type { InvoiceItem } from '@/types';

// ─── Types ─────────────────────────────

export interface InvoiceData {
  agencyName: string;
  agencyAddress: string;
  agencyGST?: string;
  agencyPhone: string;
  agencyEmail: string;
  clientName: string;
  clientAddress?: string;
  clientGST?: string;
  items: InvoiceItem[];
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string;
  paymentTerms: string;
  notes?: string;
  upiId?: string;
  bankDetails?: string;
}

// ─── Generate Invoice Number ───────────

export function generateInvoiceNumber(prefix: string = 'INV'): string {
  if (typeof window === 'undefined') return `${prefix}-2026-001`;
  try {
    const year = new Date().getFullYear();
    const raw = localStorage.getItem('oracle_invoice_counter');
    const counter = raw ? parseInt(raw, 10) + 1 : 1;
    localStorage.setItem('oracle_invoice_counter', String(counter));
    return `${prefix}-${year}-${String(counter).padStart(3, '0')}`;
  } catch (e) {
    console.warn('[Invoice] Failed to read invoice counter from localStorage:', e);
    return `${prefix}-${new Date().getFullYear()}-001`;
  }
}

// ─── Calculate Invoice Totals ──────────

export function calculateInvoiceTotals(items: InvoiceItem[]) {
  const subtotal = items.reduce((sum, item) => sum + item.amount, 0);
  const gst = subtotal * 0.18;
  const total = subtotal + gst;
  return { subtotal, gst, total };
}

// ─── Generate Invoice HTML ─────────────

function buildInvoiceHTML(data: InvoiceData): string {
  const { subtotal, gst, total } = calculateInvoiceTotals(data.items);

  const itemsHTML = data.items.map((item) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#374151">${item.description}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#374151;text-align:center">${item.quantity}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#374151;text-align:right">₹${item.rate.toLocaleString('en-IN')}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#111827;text-align:right;font-weight:600">₹${item.amount.toLocaleString('en-IN')}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:40px;font-family:'Inter',system-ui,sans-serif;background:#fff;color:#111">
  <div style="max-width:800px;margin:0 auto">
    <!-- Header -->
    <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #4f46e5">
      <div>
        <h1 style="margin:0;font-size:28px;font-weight:800;color:#4f46e5;letter-spacing:-0.5px">INVOICE</h1>
        <p style="margin:4px 0 0;font-size:11px;color:#9ca3af;letter-spacing:1px;text-transform:uppercase">Generated by ORACLE</p>
      </div>
      <div style="text-align:right">
        <p style="margin:0;font-size:13px;color:#6b7280"><strong>Invoice #:</strong> ${data.invoiceNumber}</p>
        <p style="margin:4px 0 0;font-size:13px;color:#6b7280"><strong>Date:</strong> ${data.invoiceDate}</p>
        <p style="margin:4px 0 0;font-size:13px;color:#6b7280"><strong>Due:</strong> ${data.dueDate}</p>
      </div>
    </div>

    <!-- From / To -->
    <div style="display:flex;gap:40px;margin-bottom:32px">
      <div style="flex:1">
        <p style="margin:0 0 8px;font-size:11px;font-weight:600;color:#9ca3af;letter-spacing:1px;text-transform:uppercase">From</p>
        <p style="margin:0;font-size:15px;font-weight:700;color:#111">${data.agencyName}</p>
        <p style="margin:4px 0 0;font-size:12px;color:#6b7280;white-space:pre-line">${data.agencyAddress}</p>
        ${data.agencyGST ? `<p style="margin:4px 0 0;font-size:12px;color:#6b7280"><strong>GSTIN:</strong> ${data.agencyGST}</p>` : ''}
        <p style="margin:4px 0 0;font-size:12px;color:#6b7280">${data.agencyPhone} · ${data.agencyEmail}</p>
      </div>
      <div style="flex:1">
        <p style="margin:0 0 8px;font-size:11px;font-weight:600;color:#9ca3af;letter-spacing:1px;text-transform:uppercase">To</p>
        <p style="margin:0;font-size:15px;font-weight:700;color:#111">${data.clientName}</p>
        ${data.clientAddress ? `<p style="margin:4px 0 0;font-size:12px;color:#6b7280;white-space:pre-line">${data.clientAddress}</p>` : ''}
        ${data.clientGST ? `<p style="margin:4px 0 0;font-size:12px;color:#6b7280"><strong>GSTIN:</strong> ${data.clientGST}</p>` : ''}
      </div>
    </div>

    <!-- Items Table -->
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
      <thead>
        <tr style="background:#f3f4f6">
          <th style="padding:10px 12px;text-align:left;font-size:12px;font-weight:600;color:#374151">Description</th>
          <th style="padding:10px 12px;text-align:center;font-size:12px;font-weight:600;color:#374151">Qty</th>
          <th style="padding:10px 12px;text-align:right;font-size:12px;font-weight:600;color:#374151">Rate</th>
          <th style="padding:10px 12px;text-align:right;font-size:12px;font-weight:600;color:#374151">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${itemsHTML}
      </tbody>
    </table>

    <!-- Totals -->
    <div style="display:flex;justify-content:flex-end;margin-bottom:32px">
      <div style="width:280px">
        <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:13px;color:#6b7280">
          <span>Subtotal</span><span>₹${subtotal.toLocaleString('en-IN')}</span>
        </div>
        <div style="display:flex;justify-content:space-between;padding:8px 0;font-size:13px;color:#6b7280">
          <span>GST (18%)</span><span>₹${gst.toLocaleString('en-IN')}</span>
        </div>
        <div style="display:flex;justify-content:space-between;padding:12px 0;font-size:18px;font-weight:800;color:#111;border-top:2px solid #111;margin-top:4px">
          <span>Total</span><span>₹${total.toLocaleString('en-IN')}</span>
        </div>
      </div>
    </div>

    <!-- Payment Details -->
    <div style="background:#f9fafb;border-radius:12px;padding:20px;margin-bottom:24px">
      <h3 style="margin:0 0 12px;font-size:13px;font-weight:600;color:#374151">Payment Details</h3>
      ${data.upiId ? `<p style="margin:4px 0;font-size:12px;color:#6b7280"><strong>UPI ID:</strong> ${data.upiId}</p>` : ''}
      ${data.bankDetails ? `<p style="margin:4px 0;font-size:12px;color:#6b7280;white-space:pre-line">${data.bankDetails}</p>` : ''}
      <p style="margin:8px 0 0;font-size:12px;color:#6b7280"><strong>Payment Terms:</strong> ${data.paymentTerms}</p>
    </div>

    ${data.notes ? `
    <div style="margin-bottom:24px">
      <h3 style="margin:0 0 8px;font-size:13px;font-weight:600;color:#374151">Notes</h3>
      <p style="margin:0;font-size:12px;color:#6b7280;white-space:pre-line">${data.notes}</p>
    </div>` : ''}

    <!-- Footer -->
    <div style="text-align:center;padding-top:24px;border-top:1px solid #e5e7eb">
      <p style="margin:0;font-size:12px;color:#9ca3af">Thank you for your business!</p>
      <p style="margin:4px 0 0;font-size:11px;color:#d1d5db">This is a computer-generated invoice.</p>
    </div>
  </div>
</body>
</html>`;
}

// ─── Generate PDF via html2canvas + jsPDF ──

export async function generateInvoicePDF(data: InvoiceData): Promise<Blob | null> {
  try {
    const [{ default: jsPDF }, html2canvasModule] = await Promise.all([
      import('jspdf'),
      import('html2canvas'),
    ]);

    const html2canvas = html2canvasModule.default;
    const html = buildInvoiceHTML(data);

    // Create off-screen container
    const container = document.createElement('div');
    container.innerHTML = html;
    container.style.cssText = 'position:fixed;left:-9999px;top:0;width:800px;background:#fff';
    document.body.appendChild(container);

    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      width: 800,
    });

    document.body.removeChild(container);

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);

    return pdf.output('blob');
  } catch (e) {
    console.warn('[Invoice] Failed to generate PDF:', e);
    return null;
  }
}

// ─── Trigger Download ──────────────────

export async function downloadInvoicePDF(data: InvoiceData, filename?: string): Promise<void> {
  const blob = await generateInvoicePDF(data);
  if (!blob) return;

  const name = filename || `invoice-${data.invoiceNumber.toLowerCase()}.pdf`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Format Invoice as Text ────────────

export function formatInvoiceAsText(data: InvoiceData): string {
  const { subtotal, gst, total } = calculateInvoiceTotals(data.items);

  let text = `INVOICE ${data.invoiceNumber}\n`;
  text += `Date: ${data.invoiceDate} | Due: ${data.dueDate}\n\n`;
  text += `FROM: ${data.agencyName}\n${data.agencyAddress}\n`;
  if (data.agencyGST) text += `GSTIN: ${data.agencyGST}\n`;
  text += `${data.agencyPhone} | ${data.agencyEmail}\n\n`;
  text += `TO: ${data.clientName}\n`;
  if (data.clientAddress) text += `${data.clientAddress}\n`;
  if (data.clientGST) text += `GSTIN: ${data.clientGST}\n`;
  text += `\n${'─'.repeat(50)}\n`;
  text += `Description`.padEnd(30) + `Qty`.padStart(5) + `Rate`.padStart(12) + `Amount`.padStart(12) + `\n`;
  text += `${'─'.repeat(50)}\n`;

  for (const item of data.items) {
    text += item.description.padEnd(30) +
      String(item.quantity).padStart(5) +
      `₹${item.rate.toLocaleString('en-IN')}`.padStart(12) +
      `₹${item.amount.toLocaleString('en-IN')}`.padStart(12) + `\n`;
  }

  text += `${'─'.repeat(50)}\n`;
  text += `Subtotal`.padEnd(47) + `₹${subtotal.toLocaleString('en-IN')}`.padStart(12) + `\n`;
  text += `GST (18%)`.padEnd(47) + `₹${gst.toLocaleString('en-IN')}`.padStart(12) + `\n`;
  text += `TOTAL`.padEnd(47) + `₹${total.toLocaleString('en-IN')}`.padStart(12) + `\n\n`;

  if (data.upiId) text += `UPI ID: ${data.upiId}\n`;
  if (data.bankDetails) text += `${data.bankDetails}\n`;
  text += `Payment Terms: ${data.paymentTerms}\n`;
  if (data.notes) text += `\nNotes: ${data.notes}\n`;
  text += `\nThank you for your business!`;

  return text;
}
